// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package v1

import (
	"time"
)

// Defines values for AssertionMethod.
const (
	AssertionMethodJSONPATH AssertionMethod = "JSONPATH"
)

// Defines values for ErrorSlug.
const (
	ErrorSlugBadRequest ErrorSlug = "bad-request"

	ErrorSlugEmptyBearerToken ErrorSlug = "empty-bearer-token"

	ErrorSlugInvalidJson ErrorSlug = "invalid-json"

	ErrorSlugInvalidSpecificationSource ErrorSlug = "invalid-specification-source"

	ErrorSlugPerformanceAlreadyStarted ErrorSlug = "performance-already-started"

	ErrorSlugPerformanceNotFound ErrorSlug = "performance-not-found"

	ErrorSlugSpecificationNotFound ErrorSlug = "specification-not-found"

	ErrorSlugTestCampaignNotFound ErrorSlug = "test-campaign-not-found"

	ErrorSlugUnableToVerifyJwt ErrorSlug = "unable-to-verify-jwt"

	ErrorSlugUnauthorizedUser ErrorSlug = "unauthorized-user"

	ErrorSlugUnexpectedError ErrorSlug = "unexpected-error"

	ErrorSlugUserCantSeePerformance ErrorSlug = "user-cant-see-performance"

	ErrorSlugUserCantSeeTestCampaign ErrorSlug = "user-cant-see-test-campaign"
)

// Defines values for HttpMethod.
const (
	HttpMethodCONNECT HttpMethod = "CONNECT"

	HttpMethodDELETE HttpMethod = "DELETE"

	HttpMethodGET HttpMethod = "GET"

	HttpMethodHEAD HttpMethod = "HEAD"

	HttpMethodOPTIONS HttpMethod = "OPTIONS"

	HttpMethodPATCH HttpMethod = "PATCH"

	HttpMethodPOST HttpMethod = "POST"

	HttpMethodPUT HttpMethod = "PUT"

	HttpMethodTRACE HttpMethod = "TRACE"
)

// Defines values for PerformanceState.
const (
	PerformanceStateNOTPERFORMED PerformanceState = "NOT_PERFORMED"

	PerformanceStatePERFORMING PerformanceState = "PERFORMING"

	PerformanceStatePERFORMINGERROR PerformanceState = "PERFORMING_ERROR"

	PerformanceStatePERFORMINGFAILED PerformanceState = "PERFORMING_FAILED"

	PerformanceStatePERFORMINGPASSED PerformanceState = "PERFORMING_PASSED"
)

// Assert defines model for Assert.
type Assert struct {
	Actual   string `json:"actual"`
	Expected string `json:"expected"`
}

// Assertion defines model for Assertion.
type Assertion struct {
	Assert []Assert        `json:"assert"`
	With   AssertionMethod `json:"with"`
}

// AssertionMethod defines model for AssertionMethod.
type AssertionMethod string

// CreateTestCampaignRequest defines model for CreateTestCampaignRequest.
type CreateTestCampaignRequest struct {
	Summary  *string `json:"summary,omitempty"`
	ViewName string  `json:"viewName"`
}

// Error defines model for Error.
type Error struct {
	Details string    `json:"details"`
	Slug    ErrorSlug `json:"slug"`
}

// ErrorSlug defines model for ErrorSlug.
type ErrorSlug string

// Http defines model for Http.
type Http struct {
	Request  *HttpRequest  `json:"request,omitempty"`
	Response *HttpResponse `json:"response,omitempty"`
}

// HttpMethod defines model for HttpMethod.
type HttpMethod string

// HttpRequest defines model for HttpRequest.
type HttpRequest struct {
	Body        *map[string]interface{} `json:"body,omitempty"`
	ContentType *string                 `json:"contentType,omitempty"`
	Method      HttpMethod              `json:"method"`
	Url         string                  `json:"url"`
}

// HttpResponse defines model for HttpResponse.
type HttpResponse struct {
	AllowedCodes       []int   `json:"allowedCodes"`
	AllowedContentType *string `json:"allowedContentType,omitempty"`
}

// PerformanceResponse defines model for PerformanceResponse.
type PerformanceResponse struct {
	State              *PerformanceState   `json:"state,omitempty"`
	StoriesPerformance *[]StoryPerformance `json:"storiesPerformance,omitempty"`
}

// PerformanceState defines model for PerformanceState.
type PerformanceState string

// Scenario defines model for Scenario.
type Scenario struct {
	Description *string  `json:"description,omitempty"`
	Slug        string   `json:"slug"`
	Theses      []Thesis `json:"theses"`
}

// ScenarioPerformance defines model for ScenarioPerformance.
type ScenarioPerformance struct {
	Slug              string               `json:"slug"`
	State             PerformanceState     `json:"state"`
	ThesesPerformance *[]ThesisPerformance `json:"thesesPerformance,omitempty"`
}

// Specification defines model for Specification.
type Specification struct {
	Author         *string   `json:"author,omitempty"`
	Description    *string   `json:"description,omitempty"`
	Id             string    `json:"id"`
	LoadedAt       time.Time `json:"loadedAt"`
	Stories        []Story   `json:"stories"`
	TestCampaignId string    `json:"testCampaignId"`
	Title          *string   `json:"title,omitempty"`
}

// SpecificationResponse defines model for SpecificationResponse.
type SpecificationResponse struct {
	SourceUri     string        `json:"sourceUri"`
	Specification Specification `json:"specification"`
}

// SpecificationSource defines model for SpecificationSource.
type SpecificationSource string

// Statement defines model for Statement.
type Statement struct {
	Behavior string `json:"behavior"`
	Keyword  string `json:"keyword"`
}

// Story defines model for Story.
type Story struct {
	AsA         *string    `json:"asA,omitempty"`
	Description *string    `json:"description,omitempty"`
	InOrderTo   *string    `json:"inOrderTo,omitempty"`
	Scenarios   []Scenario `json:"scenarios"`
	Slug        string     `json:"slug"`
	WantTo      *string    `json:"wantTo,omitempty"`
}

// StoryPerformance defines model for StoryPerformance.
type StoryPerformance struct {
	ScenariosPerformance *[]ScenarioPerformance `json:"scenariosPerformance,omitempty"`
	Slug                 string                 `json:"slug"`
	State                PerformanceState       `json:"state"`
}

// TestCampaignResponse defines model for TestCampaignResponse.
type TestCampaignResponse struct {
	CreatedAt         time.Time `json:"createdAt"`
	Id                string    `json:"id"`
	LastPerformanceId *string   `json:"lastPerformanceId,omitempty"`
	Summary           *string   `json:"summary,omitempty"`
	ViewName          string    `json:"viewName"`
}

// Thesis defines model for Thesis.
type Thesis struct {
	After     []string   `json:"after"`
	Assertion *Assertion `json:"assertion,omitempty"`
	Http      *Http      `json:"http,omitempty"`
	Slug      string     `json:"slug"`
	Statement Statement  `json:"statement"`
}

// ThesisPerformance defines model for ThesisPerformance.
type ThesisPerformance struct {
	ErrorDetails *string          `json:"errorDetails,omitempty"`
	FailDetails  *string          `json:"failDetails,omitempty"`
	Slug         string           `json:"slug"`
	State        PerformanceState `json:"state"`
}

// CreateTestCampaignJSONBody defines parameters for CreateTestCampaign.
type CreateTestCampaignJSONBody CreateTestCampaignRequest

// CreateTestCampaignJSONRequestBody defines body for CreateTestCampaign for application/json ContentType.
type CreateTestCampaignJSONRequestBody CreateTestCampaignJSONBody
