// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns performance with such ID.
	// (GET /performances/{performanceId})
	GetPerformance(w http.ResponseWriter, r *http.Request, performanceId string)
	// Restart performance with such ID.
	// (PUT /performances/{performanceId})
	RestartPerformance(w http.ResponseWriter, r *http.Request, performanceId string)
	// Cancels performance with such ID.
	// (PUT /performances/{performanceId}/canceled)
	CancelPerformance(w http.ResponseWriter, r *http.Request, performanceId string)
	// Returns specification with such ID.
	// (GET /specifications/{specificationId})
	GetSpecification(w http.ResponseWriter, r *http.Request, specificationId string)
	// Returns test campaigns.
	// (GET /test-campaigns)
	GetTestCampaigns(w http.ResponseWriter, r *http.Request)
	// Creates test campaign for testing services logic using BDD specification style.
	// (POST /test-campaigns)
	CreateTestCampaign(w http.ResponseWriter, r *http.Request)
	// Removes test campaign with such ID.
	// (DELETE /test-campaigns/{testCampaignId})
	RemoveTestCampaign(w http.ResponseWriter, r *http.Request, testCampaignId string)
	// Returns test campaign with such ID.
	// (GET /test-campaigns/{testCampaignId})
	GetTestCampaign(w http.ResponseWriter, r *http.Request, testCampaignId string)
	// Asynchronously starts performing of test campaign active specification performance.
	// (POST /test-campaigns/{testCampaignId}/performance)
	StartPerformance(w http.ResponseWriter, r *http.Request, testCampaignId string)
	// Returns performance history.
	// (GET /test-campaigns/{testCampaignId}/performances)
	GetPerformanceHistory(w http.ResponseWriter, r *http.Request, testCampaignId string)
	// Loads specification to test campaign.
	// (POST /test-campaigns/{testCampaignId}/specification)
	LoadSpecification(w http.ResponseWriter, r *http.Request, testCampaignId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetPerformance operation middleware
func (siw *ServerInterfaceWrapper) GetPerformance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "performanceId" -------------
	var performanceId string

	err = runtime.BindStyledParameter("simple", false, "performanceId", chi.URLParam(r, "performanceId"), &performanceId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPerformance(w, r, performanceId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// RestartPerformance operation middleware
func (siw *ServerInterfaceWrapper) RestartPerformance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "performanceId" -------------
	var performanceId string

	err = runtime.BindStyledParameter("simple", false, "performanceId", chi.URLParam(r, "performanceId"), &performanceId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartPerformance(w, r, performanceId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CancelPerformance operation middleware
func (siw *ServerInterfaceWrapper) CancelPerformance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "performanceId" -------------
	var performanceId string

	err = runtime.BindStyledParameter("simple", false, "performanceId", chi.URLParam(r, "performanceId"), &performanceId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelPerformance(w, r, performanceId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetSpecification operation middleware
func (siw *ServerInterfaceWrapper) GetSpecification(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "specificationId" -------------
	var specificationId string

	err = runtime.BindStyledParameter("simple", false, "specificationId", chi.URLParam(r, "specificationId"), &specificationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "specificationId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpecification(w, r, specificationId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetTestCampaigns operation middleware
func (siw *ServerInterfaceWrapper) GetTestCampaigns(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTestCampaigns(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateTestCampaign operation middleware
func (siw *ServerInterfaceWrapper) CreateTestCampaign(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTestCampaign(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// RemoveTestCampaign operation middleware
func (siw *ServerInterfaceWrapper) RemoveTestCampaign(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "testCampaignId" -------------
	var testCampaignId string

	err = runtime.BindStyledParameter("simple", false, "testCampaignId", chi.URLParam(r, "testCampaignId"), &testCampaignId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "testCampaignId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveTestCampaign(w, r, testCampaignId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetTestCampaign operation middleware
func (siw *ServerInterfaceWrapper) GetTestCampaign(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "testCampaignId" -------------
	var testCampaignId string

	err = runtime.BindStyledParameter("simple", false, "testCampaignId", chi.URLParam(r, "testCampaignId"), &testCampaignId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "testCampaignId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTestCampaign(w, r, testCampaignId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// StartPerformance operation middleware
func (siw *ServerInterfaceWrapper) StartPerformance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "testCampaignId" -------------
	var testCampaignId string

	err = runtime.BindStyledParameter("simple", false, "testCampaignId", chi.URLParam(r, "testCampaignId"), &testCampaignId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "testCampaignId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartPerformance(w, r, testCampaignId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPerformanceHistory operation middleware
func (siw *ServerInterfaceWrapper) GetPerformanceHistory(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "testCampaignId" -------------
	var testCampaignId string

	err = runtime.BindStyledParameter("simple", false, "testCampaignId", chi.URLParam(r, "testCampaignId"), &testCampaignId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "testCampaignId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPerformanceHistory(w, r, testCampaignId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// LoadSpecification operation middleware
func (siw *ServerInterfaceWrapper) LoadSpecification(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "testCampaignId" -------------
	var testCampaignId string

	err = runtime.BindStyledParameter("simple", false, "testCampaignId", chi.URLParam(r, "testCampaignId"), &testCampaignId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "testCampaignId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadSpecification(w, r, testCampaignId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/performances/{performanceId}", wrapper.GetPerformance)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/performances/{performanceId}", wrapper.RestartPerformance)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/performances/{performanceId}/canceled", wrapper.CancelPerformance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/specifications/{specificationId}", wrapper.GetSpecification)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-campaigns", wrapper.GetTestCampaigns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/test-campaigns", wrapper.CreateTestCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/test-campaigns/{testCampaignId}", wrapper.RemoveTestCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-campaigns/{testCampaignId}", wrapper.GetTestCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/test-campaigns/{testCampaignId}/performance", wrapper.StartPerformance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-campaigns/{testCampaignId}/performances", wrapper.GetPerformanceHistory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/test-campaigns/{testCampaignId}/specification", wrapper.LoadSpecification)
	})

	return r
}
