version: '3.4'

networks:
  back-tier:
  front-tier:

services:
  thestis:
    image: thestis
    container_name: thestis
    build:
      context: .
      dockerfile: ./build/package/dev/Dockerfile
    networks:
      - back-tier
    ports:
      - '8000:8000'
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
      - ./swagger/:/root/swagger/
      - ./.secrets/:/root/.secrets/ # Path to service account file
    depends_on:
      - mongodb
      - prometheus
      - grafana
      - nats
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=thestis
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - ./.data/db:/data/db
    networks:
      - back-tier
    ports:
      - '27018:27017'

  nats:
    image: nats:latest
    container_name: nats-server
    networks:
      - back-tier
    ports:
      - '14222:8222'
      - '18222:8222'
      - '16222:6222'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.data/prometheus:/prometheus
    ports:
      - '9090:9090'
    networks:
      - back-tier
    depends_on:
      - prometheus-node-exporter

  prometheus-node-exporter:
    image: prom/node-exporter
    container_name: prometheus-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - back-tier
    ports:
      - '9100:9100'

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./.data/grafana:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    ports:
      - '3000:3000'
