// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package v1

import (
	"time"
)

// Defines values for AssertionMethod.
const (
	AssertionMethodJSONPATH AssertionMethod = "JSONPATH"
)

// Defines values for ErrorSlug.
const (
	ErrorSlugBadRequest ErrorSlug = "bad-request"

	ErrorSlugEmptyBearerToken ErrorSlug = "empty-bearer-token"

	ErrorSlugInvalidJson ErrorSlug = "invalid-json"

	ErrorSlugInvalidSpecificationSource ErrorSlug = "invalid-specification-source"

	ErrorSlugPipelineAlreadyStarted ErrorSlug = "pipeline-already-started"

	ErrorSlugPipelineNotFound ErrorSlug = "pipeline-not-found"

	ErrorSlugPipelineNotStarted ErrorSlug = "pipeline-not-started"

	ErrorSlugSpecificationNotFound ErrorSlug = "specification-not-found"

	ErrorSlugTestCampaignNotFound ErrorSlug = "test-campaign-not-found"

	ErrorSlugUnableToVerifyJwt ErrorSlug = "unable-to-verify-jwt"

	ErrorSlugUnauthorizedUser ErrorSlug = "unauthorized-user"

	ErrorSlugUnexpectedError ErrorSlug = "unexpected-error"

	ErrorSlugUserCantSeePipeline ErrorSlug = "user-cant-see-pipeline"

	ErrorSlugUserCantSeeTestCampaign ErrorSlug = "user-cant-see-test-campaign"
)

// Defines values for HttpMethod.
const (
	HttpMethodCONNECT HttpMethod = "CONNECT"

	HttpMethodDELETE HttpMethod = "DELETE"

	HttpMethodGET HttpMethod = "GET"

	HttpMethodHEAD HttpMethod = "HEAD"

	HttpMethodOPTIONS HttpMethod = "OPTIONS"

	HttpMethodPATCH HttpMethod = "PATCH"

	HttpMethodPOST HttpMethod = "POST"

	HttpMethodPUT HttpMethod = "PUT"

	HttpMethodTRACE HttpMethod = "TRACE"
)

// Defines values for PipelineState.
const (
	PipelineStateCANCELED PipelineState = "CANCELED"

	PipelineStateCRASHED PipelineState = "CRASHED"

	PipelineStateEXECUTING PipelineState = "EXECUTING"

	PipelineStateFAILED PipelineState = "FAILED"

	PipelineStateNOSTATE PipelineState = "NO_STATE"

	PipelineStateNOTEXECUTED PipelineState = "NOT_EXECUTED"

	PipelineStatePASSED PipelineState = "PASSED"

	PipelineStateQUEUED PipelineState = "QUEUED"
)

// Assert defines model for Assert.
type Assert struct {
	Actual   string `json:"actual"`
	Expected string `json:"expected"`
}

// Assertion defines model for Assertion.
type Assertion struct {
	Assert []Assert        `json:"assert"`
	With   AssertionMethod `json:"with"`
}

// AssertionMethod defines model for AssertionMethod.
type AssertionMethod string

// CreateTestCampaignRequest defines model for CreateTestCampaignRequest.
type CreateTestCampaignRequest struct {
	Summary  *string `json:"summary,omitempty"`
	ViewName string  `json:"viewName"`
}

// Error defines model for Error.
type Error struct {
	Details string    `json:"details"`
	Slug    ErrorSlug `json:"slug"`
}

// ErrorSlug defines model for ErrorSlug.
type ErrorSlug string

// Flow defines model for Flow.
type Flow struct {
	OverallState PipelineState `json:"overallState"`
	Statuses     []Status      `json:"statuses"`
}

// GeneralPipelineResponse defines model for GeneralPipelineResponse.
type GeneralPipelineResponse struct {
	Id              string        `json:"id"`
	LastState       PipelineState `json:"lastState"`
	SpecificationId string        `json:"specificationId"`
	StartedAt       time.Time     `json:"startedAt"`
}

// Http defines model for Http.
type Http struct {
	Request  *HttpRequest  `json:"request,omitempty"`
	Response *HttpResponse `json:"response,omitempty"`
}

// HttpMethod defines model for HttpMethod.
type HttpMethod string

// HttpRequest defines model for HttpRequest.
type HttpRequest struct {
	Body        *map[string]interface{} `json:"body,omitempty"`
	ContentType *string                 `json:"contentType,omitempty"`
	Method      HttpMethod              `json:"method"`
	Url         string                  `json:"url"`
}

// HttpResponse defines model for HttpResponse.
type HttpResponse struct {
	AllowedCodes       []int   `json:"allowedCodes"`
	AllowedContentType *string `json:"allowedContentType,omitempty"`
}

// PipelineState defines model for PipelineState.
type PipelineState string

// Scenario defines model for Scenario.
type Scenario struct {
	Description *string  `json:"description,omitempty"`
	Slug        string   `json:"slug"`
	Theses      []Thesis `json:"theses"`
}

// SpecificPipelineResponse defines model for SpecificPipelineResponse.
type SpecificPipelineResponse struct {
	Flows           interface{} `json:"flows"`
	Id              string      `json:"id"`
	SpecificationId string      `json:"specificationId"`
}

// Specification defines model for Specification.
type Specification struct {
	Author         *string   `json:"author,omitempty"`
	Description    *string   `json:"description,omitempty"`
	Id             string    `json:"id"`
	LoadedAt       time.Time `json:"loadedAt"`
	Stories        []Story   `json:"stories"`
	TestCampaignId string    `json:"testCampaignId"`
	Title          *string   `json:"title,omitempty"`
}

// SpecificationResponse defines model for SpecificationResponse.
type SpecificationResponse struct {
	SourceUri     string        `json:"sourceUri"`
	Specification Specification `json:"specification"`
}

// SpecificationSlug defines model for SpecificationSlug.
type SpecificationSlug struct {
	Scenario *string `json:"scenario,omitempty"`
	Story    *string `json:"story,omitempty"`
	Thesis   *string `json:"thesis,omitempty"`
}

// SpecificationSource defines model for SpecificationSource.
type SpecificationSource string

// StartPipelineRequest defines model for StartPipelineRequest.
type StartPipelineRequest struct {
	ScenarioSlugs *interface{} `json:"scenarioSlugs,omitempty"`
}

// Statement defines model for Statement.
type Statement struct {
	Behavior string `json:"behavior"`
	Stage    string `json:"stage"`
}

// Status defines model for Status.
type Status struct {
	Slug           SpecificationSlug `json:"slug"`
	State          PipelineState     `json:"state"`
	ThesisStatuses interface{}       `json:"thesisStatuses"`
}

// Story defines model for Story.
type Story struct {
	AsA         *string    `json:"asA,omitempty"`
	Description *string    `json:"description,omitempty"`
	InOrderTo   *string    `json:"inOrderTo,omitempty"`
	Scenarios   []Scenario `json:"scenarios"`
	Slug        string     `json:"slug"`
	WantTo      *string    `json:"wantTo,omitempty"`
}

// TestCampaignResponse defines model for TestCampaignResponse.
type TestCampaignResponse struct {
	CreatedAt      time.Time `json:"createdAt"`
	Id             string    `json:"id"`
	LastPipelineId *string   `json:"lastPipelineId,omitempty"`
	Summary        *string   `json:"summary,omitempty"`
	ViewName       string    `json:"viewName"`
}

// Thesis defines model for Thesis.
type Thesis struct {
	After     []string   `json:"after"`
	Assertion *Assertion `json:"assertion,omitempty"`
	Http      *Http      `json:"http,omitempty"`
	Slug      string     `json:"slug"`
	Statement Statement  `json:"statement"`
}

// ThesisStatus defines model for ThesisStatus.
type ThesisStatus struct {
	OccurredErrors interface{}   `json:"occurredErrors"`
	State          PipelineState `json:"state"`
	ThesisSlug     string        `json:"thesisSlug"`
}

// CreateTestCampaignJSONBody defines parameters for CreateTestCampaign.
type CreateTestCampaignJSONBody CreateTestCampaignRequest

// StartPipelineJSONBody defines parameters for StartPipeline.
type StartPipelineJSONBody StartPipelineRequest

// CreateTestCampaignJSONRequestBody defines body for CreateTestCampaign for application/json ContentType.
type CreateTestCampaignJSONRequestBody CreateTestCampaignJSONBody

// StartPipelineJSONRequestBody defines body for StartPipeline for application/json ContentType.
type StartPipelineJSONRequestBody StartPipelineJSONBody
