http:
  port: ${HTTP_PORT:8080}
  readTimeout: 4s
  writeTimeout: 10s
  shutdownTimeout: 10s

mongo:
  uri: ${MONGO_URI}
  databaseName: ${MONGO_DATABASE:thestis}
  username: ${MONGO_USERNAME:admin}
  password: ${MONGO_PASSWORD:qwerty}
  disconnectTimeout: 10s

auth:
  with: ${AUTH_TYPE:firebase}
firebase:
  serviceAccountFile: ${SERVICE_ACCOUNT_FILE}

performance:
  flowTimeout: 24h
  policy: savePerStep
  signalBus: nats
  workers: 10
savePerStep:
  saveTimeout: 30s
nats:
  url: nats://nats:4222
